### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mstyne** [Gutza/php-zookeeper-recipes#2]
Hi @Gutza!

Would you consider a establishing an Apache, MIT, or LGPL license  for your `php-zookeeper-recipes` code so that it can be used in commercial software products?

I'm currently implementing advisory locking for our application and it would be great to be able to use your `ZR_Xlock` class.

Thanks,
Mike

**Comment by Gutza** [comment]
Hi,

I'll gladly license it to you for free if you're willing to participate in any small way to the code base.

Best,
Bogdan

**Comment by mstyne** [comment]
Certainly! 

At present exclusive locks seem to be functioning just as they should, but if we need to make any changes once the code is used in a production capacity, I would be happy to contribute them back to the project.

Thanks again,
Mike

**Comment by Gutza** [comment]
Mike, that's not it – what you're describing is the standard open source model you've been asking for all along (you use the code, and if you're so inclined, you contribute back). But see, I'm a bastard – I'm asking you to make some contribution beforehand. Pick whatever you're most comfortable with – write a couple of examples, document some details that you found interesting, or particularly challenging to understand, or whatever you feel like. Just send in a pull request that makes sense; as soon as I merge your patch, you can consider the entity which pays for your time licensed under LGPL.

**Comment by mstyne** [comment]
Understood.

I'll submit a (hopefully useful) pull request in the coming days.

Thanks,
Mike

**Comment by Gutza** [comment]
Thanks Mike, that's good enough for me. Please let me know if you need a formal e-mail confirming your license.

Cheers,
Bogdan

**Comment by mstyne** [comment]
Bogdan,

Thanks again; I'll cite the two Github issues in our documentation -- that should do the trick.

Have a good weekend,
Mike
